export const APP_LOADING = 'APP_LOADING'
export const APP_TITLE = 'APP_TITLE'
export const APP_DIRECTION = 'APP_DIRECTION'
export const APP_LANG = 'APP_LANG'
export const APP_ASIDE_CLOSE = 'APP_ASIDE_CLOSE'